server {
    listen 80;

    # Route API requests to the backend
    location /api/ {
        proxy_pass https://reci-pa-ispeci-be.onrender.com/; # Use your backend's URL
        proxy_ssl_server_name on;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 2m;
    }

    # Serve frontend assets and handle frontend routing
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
